### ISSUE TITLE
Potentially find a widely used alternative of Capsule

### ISSUE THREAD

**Issue by tk26** [trycourier/courier-php#7]
We use https://github.com/nimbly/Capsule/ for building the outbound HTTP requests. There's a little risk in relying on Capsule because its not a popular dependency (just has 1 star on GH) - maybe we can find a better/widely used alternative and replace it?

**Comment by slashequip** [comment]
Fairly sure https://github.com/Nyholm/psr7 is almost the goto at this point.

### Alternative;
I believe the point of PSR17 is that you shouldn't provide concrete implementation in _your_ package but encourage the consumer of this package to install one in their project, giving `composer require nyholm/psr7` as an example in the documentation.

You can then use discovery https://packagist.org/packages/php-http/discovery to find the consumers implementation.

For example, replacing;
```php
if( empty($this->httpClient) ){
    $this->httpClient = new Shuttle;
}
```

With:
```php
use Http\Discovery\HttpClientDiscovery;

if( empty($this->httpClient) ){
    $this->httpClient = HttpClientDiscovery::find();
}
```

And similar for a request factory; https://docs.php-http.org/en/latest/discovery.html#psr-17-factory-discovery

I think this would be the more future proof approach now, rather than providing your own concrete implementation.

**Comment by slashequip** [comment]
If I get chance, and you are happy for me to, I'll look at putting together a PR for the PSR implementation. 🙂

Although might a few weeks off at the moment based on work and time. 😖

**Comment by tk26** [comment]
It'd be dope @slashequip - appreciate it :)

**Comment by abdul-courier** [comment]
Thanks @slashequip, you are our hero here :)
